# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "web1" do |web1|
    web1.vm.box = "base"
    web1.vm.network "private_network", ip: "192.168.50.10"
    web1.vm.network "forwarded_port", guest: 80 ,host: 8081
    web1.vm.hostname = "web1.dev"
    web1.vm.synced_folder "web1", "/vagrant"
    web1.vm.synced_folder "./files", "/etc/puppet/files"
    web1.vm.provision :puppet do |puppet|
      puppet.options = ["--fileserverconfig=/vagrant/fileserver.conf"]
    end
  end

config.vm.define "web2" do |web2|
    web2.vm.box = "base"
    web2.vm.network "private_network", ip: "192.168.50.11"
    web2.vm.network "forwarded_port", guest: 80, host: 8082
    web2.vm.hostname = "web2.dev"
    web2.vm.synced_folder "web2", "/vagrant"
    web2.vm.synced_folder "./files", "/etc/puppet/files"
    web2.vm.provision :puppet do |puppet|
      puppet.options = ["--fileserverconfig=/vagrant/fileserver.conf"]
    end
  end
end
